six_dof_arm:

 joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50    
 
 position_controller:
   type: position_controllers/JointTrajectoryController
   joints:
    - shoulder_roll_joint
    - shoulder_pitch_joint
    - elbow_roll_joint
    - elbow_pitch_joint
    - wrist_roll_joint
    - wrist_pitch_joint
   
 gazebo_ros_control:
   pid_gains:
     shoulder_roll_joint: {p: 1500, i: 0.1, d: 10}
     shoulder_pitch_joint: {p: 1500, i: 0.1, d: 10}
     elbow_roll_joint: {p: 1500, i: 0.1, d: 10}
     elbow_pitch_joint: {p: 1500, i: 0.1, d: 10}
     wrist_roll_joint: {p: 1500, i: 0.1, d: 10}
     wrist_pitch_joint: {p: 1500, i: 0.1, d: 10}
     
controller_list:
 - name: /six_dof_arm/position_controller
   action_ns: follow_joint_trajectory
   default: True
   type: FollowJointTrajectory
   joints:
    - shoulder_roll_joint
    - shoulder_pitch_joint
    - elbow_roll_joint
    - elbow_pitch_joint
    - wrist_roll_joint
    - wrist_pitch_joint
    - gripper_roll_joint   
   allowed_excution_duration_scaling: 1.2
   allowed_goal_duration_margin: 0.5
